### ISSUE TITLE
Plugin activated when creating a new content-type

### ISSUE THREAD

**Issue by Norbz** [strapi-community/strapi-plugin-url-alias#47]
### Describe the bug

When creating a new content-type, the plugin isn't activated by default. If you leave it that way, and create your content-type, then go to create an entry, the side panel is available.

Reason is, when creating a content-type, the pluginOptions isn't created if not selected. Then if the plugin option isn't found, the plugin consider to be activated by default.

### Steps to reproduce the behavior

1. Go to the content-type builder
2. Create a "testData" content-type
3. Leave the plugin url-alias unchecked
4. Go and create a new testData entry
5. Panel is showing on the right side

Workaround :
1. Go back to the content type builder
2. Check the url-alias option, save
3. Uncheck the url-alias option, save

This time the pluginOptions is being written in the shema and the plugin is working accordingly

### Additional context

Should be easily fixed by either :
- Matching the default behavior for both the admin UI (checked or unchecked) and whatever the plugin assumes when not finding any pluginOptions object.
- Write the pluginOptions when a new content-type is created, be it true or false.

**Comment by Alexnortung** [comment]
I agree, I have also experienced the same, although it didn't bother me enough to write a bug report 😅

I didn't change the default to be false, since this would be a breaking change and would require a bit more work and writing documentation of how to migrate to the new version.

I definitely think that the default should be that it is not activated. Also as you mention, the fix should actually be to show it correctly in the admin ui.
